// RatioKit/Svelte/src/lib/RatioKit/ImgText.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  /**
   * Props Definition
   */
  interface Props {
    /** クラス名 (img30, is_rev 等を指定) / Class name */
    class?: string;
    /** インラインスタイル / Inline styles */
    style?: string | Record<string, any>;
    /** 画像エリア (Snippet) / Image content */
    figure?: Snippet;
    /** コンテンツ本体 (Snippet) / Main content */
    children?: Snippet;
  }

  let { 
    class: className = "mb-0", 
    style = "", 
    figure, 
    children 
  }: Props = $props();
</script>

<div class="img_text {figure ? 'has_img' : ''} {className}" {style}>
  {#if figure}
    <figure>{@render figure()}</figure>
  {/if}
  <div>
    {@render children?.()}
  </div>
</div>

// RatioKit/Vue/ImgText.vue
<script setup lang="ts">
/**
 * ImgText コンポーネント (Image Text Component)
 * 画像 (figure) とテキストコンテンツを並べて表示します。
 */
interface Props {
  /** モディファイアクラス (img30, is_rev, bp-sm 等) */
  className?: string;
  /** インラインスタイル */
  style?: any;
}

const props = withDefaults(defineProps<Props>(), {
  className: "mb-0"
});
</script>

<template>
  <div :class="['img_text', $slots.figure ? 'has_img' : '', className]" :style="style">
    <figure v-if="$slots.figure">
      <slot name="figure"></slot>
    </figure>
    <div>
      <slot></slot>
    </div>
  </div>
</template>
