// RatioKit/Svelte/Panel.svelte
<script lang="ts">
  /**
   * Panel コンポーネント (Panel)
   * 画像とテキストのセット（ステップ表示など）を管理する親コンポーネントです。
   */
  let { 
    className = "mb-0", 
    style = {}, 
    children 
  } = $props<{
    className?: string;
    style?: any;
    children?: import('svelte').Snippet;
  }>();
</script>

<div class="panel {className}" {style}>
  {#if children}
    {@render children()}
  {/if}
</div>


<style>
  /* このコンポーネント固有のスタイルが必要な場合はここに記述してください */
</style>

// RatioKit/Vue/Panel.vue
<script setup lang="ts">
/**
 * Panel コンポーネント (Panel)
 * 画像とテキストのセット（ステップ表示など）を管理する親コンポーネントです。
 */
interface Props {
  /** モディファイアクラス (is_flow, img20, img30, bp-sm 等) */
  className?: string;
  /** インラインスタイル */
  style?: any;
}

const props = withDefaults(defineProps<Props>(), {
  className: "mb-0"
});
</script>

<template>
  <div :class="['panel', className]" :style="style">
    <slot></slot>
  </div>
</template>


<style scoped>
/* このコンポーネント固有のスタイルが必要な場合はここに記述してください */
</style>
