// RatioKit/Svelte/PanelItem.svelte
<script lang="ts">
  /**
   * PanelItem コンポーネント (Panel Item Component)
   * Panel コンポーネントの子要素です。テキストの後に画像が来る構造を持ちます。
   */
  let { 
    class: className = "", 
    style = {}, 
    figure, 
    children 
  } = $props<{
    class?: string;
    style?: any;
    figure?: import('svelte').Snippet;
    children?: import('svelte').Snippet;
  }>();
</script>

<div class="item {figure ? 'has_img' : ''} {className}" {style}>
  <div>
    {#if children}
      {@render children()}
    {/if}
  </div>
  {#if figure}
    <figure>{@render figure()}</figure>
  {/if}
</div>

// temp_zip/Vue/src/components/RatioKit/PanelItem.vue
<script setup lang="ts">
/**
 * PanelItem コンポーネント (Panel Item Component)
 * Panel コンポーネントの子要素です。テキストの後に画像が来る構造を持ちます。
 */
interface Props {
  /** モディファイアクラス (is_rev 等) */
  class?: string;
  /** インラインスタイル */
  style?: any;
}

const props = withDefaults(defineProps<Props>(), {
  class: ""
});
</script>

<template>
  <div :class="['item', $slots.figure ? 'has_img' : '', props.class]" :style="style">
    <div>
      <slot></slot>
    </div>
    <figure v-if="$slots.figure">
      <slot name="figure"></slot>
    </figure>
  </div>
</template>
