// RatioKit/Vue/Accordion.vue
<script setup lang="ts">
/**
 * Accordion コンポーネント (Accordion)
 * details/summary タグを使用した折りたたみ可能なコンテンツです。
 */
interface Props {
  /** 概要部分のテキスト */
  title: string;
  /** モディファイアクラス (is_qa, bp-sm 等) */
  class?: string;
  /** インラインスタイル */
  style?: any;
  /** 初期状態で開くかどうか */
  open?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  class: "mb-0",
  open: false
});
</script>

<template>
  <details :class="['accordion', props.class]" :style="style" :open="open">
    <summary>
      <!-- タイトル部分の画像がある場合 -->
      <div v-if="$slots.figureTitle" class="has_img">
        <figure><slot name="figureTitle"></slot></figure>
        <div>{{ title }}</div>
      </div>
      <template v-else>
        {{ title }}
      </template>
    </summary>
    <div>
      <!-- コンテンツ部分の画像がある場合 -->
      <div v-if="$slots.figure" class="has_img">
        <figure><slot name="figure"></slot></figure>
        <div><slot></slot></div>
      </div>
      <template v-else>
        <slot></slot>
      </template>
    </div>
  </details>
</template>

// RatioKit/Svelte/Accordion.svelte
<script lang="ts">
  /**
   * Accordion コンポーネント (Accordion)
   * details/summary タグを使用した折りたたみ可能なコンテンツです。
   */
  let { 
    title, 
    className = "mb-0", 
    style = {}, 
    open = false,
    figureTitle,
    figure,
    children 
  } = $props<{
    title: string;
    className?: string;
    style?: any;
    open?: boolean;
    figureTitle?: import('svelte').Snippet;
    figure?: import('svelte').Snippet;
    children?: import('svelte').Snippet;
  }>();
</script>

<details class="accordion {className}" {style} {open}>
  <summary>
    {#if figureTitle}
      <div class="has_img">
        <figure>{@render figureTitle()}</figure>
        <div>{title}</div>
      </div>
    {:else}
      {title}
    {/if}
  </summary>
  <div>
    {#if figure}
      <div class="has_img">
        <figure>{@render figure()}</figure>
        <div>
          {#if children}
            {@render children()}
          {/if}
        </div>
      </div>
    {:else if children}
      {@render children()}
    {/if}
  </div>
</details>
