// RatioKit/Vue/ImgText.vue
<script setup lang="ts">
/**
 * ImgText コンポーネント (Image Text Component)
 * 画像 (figure) とテキストコンテンツを並べて表示します。
 */
interface Props {
  /** モディファイアクラス (img30, is_rev, bp-sm 等) */
  className?: string;
  /** インラインスタイル */
  style?: any;
}

const props = withDefaults(defineProps<Props>(), {
  className: "mb-0"
});
</script>

<template>
  <div :class="['img_text', $slots.figure ? 'has_img' : '', className]" :style="style">
    <figure v-if="$slots.figure">
      <slot name="figure"></slot>
    </figure>
    <div>
      <slot></slot>
    </div>
  </div>
</template>

// edfkn/RatioKit/Svelte/ImgText.svelte
<script lang="ts">
  /**
   * ImgText コンポーネント (Image Text Component)
   * 画像 (figure) とテキストコンテンツを並べて表示します。
   */
  let { 
    className = "mb-0", 
    style = {}, 
    figure, 
    children 
  } = $props<{
    className?: string;
    style?: any;
    figure?: import('svelte').Snippet;
    children?: import('svelte').Snippet;
  }>();
</script>

<div class="img_text {figure ? 'has_img' : ''} {className}" {style}>
  {#if figure}
    <figure>{@render figure()}</figure>
  {/if}
  <div>
    {#if children}
      {@render children()}
    {/if}
  </div>
</div>
